name: 'MskConnectorAction'
description: 'Create msk connector'
inputs:
  aws-role:
    description: 'Aws role to apply changes'
    required: true
  aws-region:
    description: 'Aws region (eu-central-1, ap-northeast-1)'
    required: true
  terraform-version:
    description: 'Terraform version to install.'
    default: '1.9.7'
  terragrunt-version:
    description: 'Terragrunt version to install.'
    default: '0.68.1'
  terraform-data-one-git-url:
    description: 'terraform data one repository'
    default: 'git@gitlab.com:orisha-group/construction/advae/finalcad-one/infrastructure/terraform-data-one.git'
  terraform-data-one-ref:
    description: 'Ref to use for pulling repo terraform-data-one'
    default: ''
  github-token:
    description: 'Github token to pull package to avoid limit rate'
    default: ''
  github-ssh:
    description: 'Github ssh key to pull terragrunt from github api'
    required: true
  environment:
    description: 'Finalcad environment: production, staging, sandbox'
    required: true
  region-friendly:
    description: 'Finalcad region: frankfurt or tokyo'
    required: true
  config-file-prefix:
    description: 'Sub path for config file'
    default: 'configuration'
  pr-number:
    description: 'Pull request number, empty for push'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.10.0
      with:
        ssh-private-key: ${{ inputs.github-ssh }}
    - name: Setup SSH known hosts
      shell: bash
      run: |
        echo '::group::Setup SSH known hosts'
        [[ -d ~/.ssh ]] || mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
        echo '::endgroup::'
    - name: Checkout data repository
      uses: actions/checkout@v7
      with:
        path: 'data'
    - name: Checkout terragrunt repository
      shell: bash
      run: |
        echo '::group::Checkout terragrunt repository'
        clone_args=(
          --progress
        )
        [[ -z '${{ inputs.terraform-data-one-ref }}' ]] || clone_args+=(--branch '${{ inputs.terraform-data-one-ref }}')
        clone_args+=(
          --depth 1 \
          --no-tags \
          '${{ inputs.terraform-data-one-git-url }}' \
          'terragrunt'
        )
        git clone "${clone_args[@]}"
        echo '::endgroup::'
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false
    - name: Terragrunt Binary Installer Action
      uses: autero1/action-terragrunt@v3
      if: inputs.terragrunt-version != 'disabled'
      with:
        terragrunt-version: ${{ inputs.terragrunt-version }}
        token: ${{ inputs.github-token }}
    - name: Glues files copy
      shell: bash
      run: |
        set -e
        cp ./data/${{ inputs.config-file-prefix }}/${{ inputs.environment }}/msk-connetors.yaml ./terragrunt/msk-connetors.yaml
    - name: Configure AWS credentials for security
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-role }}
        role-session-name: OIDCSession
    - name: Setup go
      uses: actions/setup-go@v7
      with:
        token: ${{ inputs.github-token }}
        go-version: 1.18
    - name: Setup cue
      shell: bash
      run: |
        go install cuelang.org/go/cmd/cue@v0.4.3
    - name: Cue vetting
      shell: bash
      run: |
        set -e
        cue vet ./terragrunt/msk-connetors.cue ./terragrunt/msk-connetors.yaml
    - name: Terragrunt plan
      if: inputs.pr-number != ''
      id: plan
      shell: bash
      run: |
        cd ./terragrunt/${{ inputs.environment }}/${{ inputs.region-friendly }}/msk_connector
        terraform init
        terragrunt plan -out plan
        terragrunt show plan -no-color > ${{ github.workspace }}/plan.txt
      continue-on-error: true
    - name: Comment on PR
      uses: actions/github-script@v9
      if: inputs.pr-number != ''
      env:
        PLAN: ${{ steps.plan.outputs.show }}
      with:
        script: |
          const fs = require('fs')
          const data = fs.readFileSync('${{ github.workspace }}/plan.txt')
          const output = `#### Terraform Plan : \`${{ steps.plan.outcome }}\`
          <details><summary>Show Plan</summary>\n
          \`\`\`terraform\n
          ${data}
          \`\`\`\n
          </details>
          *Pushed by: @${{ github.actor }}`;
          github.rest.issues.createComment({
            issue_number: ${{ inputs.pr-number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
    - name: Terragrunt apply
      if: inputs.pr-number == ''
      shell: bash
      run: |
        cd ./terragrunt/${{ inputs.environment }}/${{ inputs.region-friendly }}/msk_connector
        terragrunt apply -auto-approve
    - name: Clear local repositories
      shell: bash
      run: |
        echo '::group::Clear local repositories'
        rm -rf './terragrunt'
        echo '::endgroup::'
