name: 'MskConnectorAction'
description: 'Create msk connector'
inputs:
  aws-role:
    description: 'Aws role to apply changes'
    default: ''
  aws-region:
    description: 'Aws region (eu-central-1, ap-northeast-1)'
    default: ''
  terraform-version:
    description: 'Terraform version to install.'
    default: '1.9.7'
  terragrunt-version:
    description: 'Terragrunt version to install.'
    default: '0.68.1'
  terraform-data-one-repo:
    description: 'terraform data one repository'
    default: 'FinalCAD/terraform-data-one'
  terraform-data-one-ref:
    description: 'Ref to use for pulling repo terraform-data-one'
    default: 'master'
  github-token:
    description: 'Github token to pull package to avoid limit rate'
    default: ''
  github-ssh:
    description: 'Github ssh key to pull terragrunt from github api'
    default: ''
  environment:
    description: 'Finalcad envrionment: production, staging, sandbox'
    default: ''
  region-friendly:
    description: 'Finalcad region: frankfurt or tokyo'
    default: ''
  config-file-prefix:
    description: 'Sub path for config file'
    default: 'configuration'
  pr-number:
    description: 'Pull rerquest number, empty for push'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Deprecated version of FinalCAD/MskConnectorAction
      shell: bash
      run: |
        echo '::error title=Deprecated version of FinalCAD/MskConnectorAction::This version of FinalCAD/MskConnectorAction is deprecated use `v2` instead.'
        exit 1
